# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_pairs_cpp <- function(n, m) {
    .Call('_newHyu625Hw3_count_pairs_cpp', PACKAGE = 'newHyu625Hw3', n, m)
}

gen_logit_cpp <- function(matrix_1, x) {
    .Call('_newHyu625Hw3_gen_logit_cpp', PACKAGE = 'newHyu625Hw3', matrix_1, x)
}

kendall_cpp <- function(x, y) {
    .Call('_newHyu625Hw3_kendall_cpp', PACKAGE = 'newHyu625Hw3', x, y)
}

matrix_kendall_cpp <- function(X) {
    .Call('_newHyu625Hw3_matrix_kendall_cpp', PACKAGE = 'newHyu625Hw3', X)
}

num_str_cpp <- function(input_num) {
    .Call('_newHyu625Hw3_num_str_cpp', PACKAGE = 'newHyu625Hw3', input_num)
}

quadratic_cpp <- function(a, b, c) {
    .Call('_newHyu625Hw3_quadratic_cpp', PACKAGE = 'newHyu625Hw3', a, b, c)
}

triangle_cpp <- function(edges) {
    .Call('_newHyu625Hw3_triangle_cpp', PACKAGE = 'newHyu625Hw3', edges)
}

